name: tbDigIn
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # Pipeline
  - python=3.9.12
  - snakemake-minimal=7.32.4
  - bwa=0.7.17
  - picard=2.27.4  # can use picard-slim when R is not required
  - fgbio-minimal=2.0.2
  - fastqc=0.11.9
  - multiqc=1.13a
  - samtools=1.15.1
  - fgsv=0.0.1
  # pytomebio
  - defopt
  # Testing
  - pytest=7.1.2
  - black=22.6.0
  - flake8=4.0.1
  - mypy=0.961
  - shellcheck=0.8.0
