name: build

on: [push]
env:
  PYTHON_VERSION: 3.9

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{env.PYTHON_VERSION}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{env.PYTHON_VERSION}}
    - name: Set up miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        auto-update-conda: true
        auto-activate-base: true
        python-version: ${{env.PYTHON_VERSION}}
    - name: Set up the conda environment
      shell: bash -l {0}
      run: |
        mamba env create -f environment.yml
    - name: Run pre-commit testing
      shell: bash -l {0}
      run: |
        conda activate tbDigIn
        bash ci/precommit.sh
